version: 2.1

workflows:
  release:
    jobs:
      - release:
          context: [shared-secrets]
          filters:
            branches:
              only: [main]

  release-please:
    jobs:
      - release-please:
          context: [shared-secrets]
          filters:
            branches:
              only: [main]
      - update-lockfile:
          context: [shared-secrets]
          filters:
            branches:
              only: [test-release-please]

  'Test & Check 🕵️‍♀️':
    jobs:
      - formatting

executors:
  node:
    docker:
      - image: cimg/node:18.10.0
  windows:
    machine:
      image: windows-server-2019-vs2019:stable
    resource_class: windows.xlarge
    shell: powershell.exe -ExecutionPolicy Bypass
  linux:
    machine:
      image: ubuntu-2004:202201-02
    resource_class: large
  macos:
    resource_class: macos.x86.medium.gen2 # new generation resources
    macos:
      xcode: 13.0.0

commands:
  npm-install-deps:
    parameters:
      command:
        description: The install command that is used
        type: string
        default: npm i
    steps:
      - restore_cache:
          keys:
            - npm-{{ arch }}-v1-{{ checksum "package-lock.json" }}
            - npm-{{ arch }}-v1
      - run: << parameters.command >>
      - save_cache:
          key: npm-{{ arch }}-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

jobs:
  release:
    description: The release action that runs on the main branch
    executor: node
    steps:
      - checkout
      - npm-install-deps
      - run: npm run build
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: npx lerna publish from-package --yes --no-private
      - run:
          name: Create Github Release
          command: |
            npx release-please github-release \
              --token "${GITHUB_RELEASES_TOKEN}" \
              --repo-url "${CIRCLE_REPOSITORY_URL}" \

  release-please:
    description: Update and creates release PRs on the main branch
    executor: node
    steps:
      - checkout
      - run:
          name: Run release-please
          command: |
            npx release-please release-pr \
              --token "${GITHUB_RELEASES_TOKEN}" \
              --repo-url "${CIRCLE_REPOSITORY_URL}" \

  update-lockfile:
    description: Update lockfile in a release please PR
    executor: node
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 'a8:63:99:a7:16:fa:73:22:fc:a3:91:4c:c9:49:87:68'
      - run: npm install
      - run:
          name: Commit and push lockfile
          command: |
            git config user.name "$(git log -n 1 --pretty=format:%an)" && \
            git config user.email "$(git log -n 1 --pretty=format:%ae)" && \
            git branch --set-upstream-to=origin/test-release-please test-release-please
            git add package-lock.json && \
            git commit --amend --no-edit && \
            git push --force

  formatting:
    description: Checks if the codebase satisfies wit the lint and style rules
    executor: node
    steps:
      - checkout
      - npm-install-deps
      - run: npm run format:ci
      - run: npm run lint:ci
